### ISSUE TITLE
Microservices, Message Brokers, and Protobuf with Rust

### ISSUE THREAD

**Issue by r-zig** [szabgab/rust.org.il#10]
Title: How to use NATS and Protobuf with Rust to integrate with Microservices

## Description:
In this presentation, we'll explore how to use Protobuf and NATS to create a distributed system with microservices. We'll cover integrating with existing services to leverage them for faster development and reduced errors, demonstrating the benefits of using these technologies for scalable and efficient communication within a microservices architecture.

## Length:
20 minutes

## On-line or in-person?
in-person

## Date?
23/06/2024

## Who are  you?

I am a Software Engineer, Architect, and Independent Software Consultant. I have extensive experience developing in .NET and, in recent years, have focused on building distributed systems using Rust. I am particularly interested in P2P and decentralized networks.

Linkedin Account: https://www.linkedin.com/in/ron-zigelman/
Github: https://github.com/r-zig
e-mail: roniz.net@gmail.com

**Comment by szabgab** [comment]
Done on 2024.06.23 Thank you
