### ISSUE TITLE
Rust on Android experience

### ISSUE THREAD

**Issue by barakplasma** [szabgab/rust.org.il#12]
## Description:

Lightning talk about rust on Android experience. As a full stack web developer who doesn't know Java or want to learn Android development, I still wanted to write something that could run in the background on my Android phone. Since I know a bit of rust I decided to write the rain forecast utility as a command line program that I could run on my phone in the background using automate and termux. There's an accompanying [open source repo](https://github.com/barakplasma/israel-weather-rs) that I can demonstrate as well.

## Length:

I can talk for 5 minutes or up to 20 minutes. If I talk about 5 minutes I'll just briefly go over the experience. If I go with the 20 minute option I'll talk about how I did the build using GitHub actions, and the alternatives I considered as well.

## On-line or in-person?

Either is good, I have a slight preference to in person so that I can answer questions

## Date?

January 12th 2025 works, but another date is fine too

## Who are  you?

I'm a full stack web developer currently freelance. I'm barakplasma on GitHub, there's a link to my LinkedIn in my GitHub profile.

**Comment by szabgab** [comment]
Why did you close this issue? You don't want to give this presentation?

**Comment by szabgab** [comment]
you could reopen it and and under "date" you could put something like "February 15 or later"
