### ISSUE TITLE
Bridging Rust and C++ with cxx

### ISSUE THREAD

**Issue by IgKh** [szabgab/rust.org.il#13]
## Description:

Introduction to using the [cxx](https://cxx.rs) crate for creting direct, "safe", bi-directional FFI bindings between Rust and C++.

Draft Agenda:

* Exploring the problem space, and `cxx`'s specific approach to it.
* Looking at a small, yet real-world example.
* Architectural concerns ("Who is driving the linker?")
* Time permitting: the bigger ecosystem - [autocxx](https://github.com/google/autocxx), [cxx-qt](https://github.com/KDAB/cxx-qt), [Corrosion](https://corrosion-rs.github.io/corrosion/).

## Length:

30 minutes or more.

## On-line or in-person?

In person.

## Date?

No preference.

## Who are  you?

I am currently a senior backend engineer at a startup company, with about 10 years experience writing C++ (and Rust for much less so). However this talk has no relationship to that, and will not represent my employer.

[LinkedIn Profile](https://www.linkedin.com/in/igor-khanin-2924a221a/)

**Comment by szabgab** [comment]
Thanks for this proposal. Could you include your LinkedIn profile as well, please so I can add it to our site?

**Comment by IgKh** [comment]
Sorry for the delay, have been under the weather. Added a link to LinkedIn. Either language is fine, though I prefer to work with an English slide deck for such topics.

**Comment by szabgab** [comment]
I've scheduled this. If you'd like to make changes to the info, please send a PR.
