### ISSUE TITLE
[Talk] TauiJS capabilities live demo.

### ISSUE THREAD

**Issue by dolev146** [szabgab/rust.org.il#14]
Title: TauiJS capabilities live demo.
link:
https://v2.tauri.app/

Create small, fast, secure, cross-platform applications

with the front end framework by rust Yew

link:
https://yew.rs/

## Description:

This presentation will present a demo of the Taurijs library, a tool built with Rust that competes with ElectroneJS to compile a web app into a native app for computers, phones, tablets, etc., making it easier to produce an app on one codebase.

## Length:

40 min , preferred to be mainly in English, but will mix Hebrew

## On-line or in-person?

I want my presentation to be recorded and also face-to-face to interact with the audience.
My main priority is to record so I can put that on my resume to assist me get a job.

## Date?

the date will be : 12.1 
From Gabor, before my flight to ski.

## Who are you?

Dolev Dublon, 

Age 25 master computer science student and a software engineer looking for a job. 2 years experience. last project at my job I focused on building a medical tool in a surgery room to visualize for the doctor Lead Implantation in the brain in real-time for Parkinson's disease. 

https://github.com/dolev146
https://stackoverflow.com/users/13104490/dolev-dublon
dolev146@gmail.com

**Comment by szabgab** [comment]
scheduled. If you would like to make changes, please send a PR.

**Comment by dolev146** [comment]
Hey Gabor I think I will talk mainly in Hebrew, it will be harder in English, is it OK?

**Comment by szabgab** [comment]
Hebrew is our default language. It is you who wanted to talk in English.
So yes it would be ok to speak in Hebrew.
