### ISSUE TITLE
Are We Embedded Yet? - Implementing tiny HTTP server on a microcontroller

### ISSUE THREAD

**Issue by maor1993** [szabgab/rust.org.il#8]
# Are We Embedded Yet? - Implementing tiny HTTP server on a microcontroller

## Description:
Given Rust's destiny to become the go-to replacement for C, a clear target for such a change would be the world of embedded microcontrollers.
we sometimes tend to ignore these devices, but they cover so much of our basic appliances and they all are running C.
The embedded world is notorious for its lack of capabilities of reuse and following proper safe code guidelines. this is especially true when most Embedded C developers use many tricks to get the most optimal result in regards to speed and size.

I wanted to try and leverage the power of Rust to show both its capabilities to create advanced projects easily, and do so in a "safe" manner.

I will show an example project, done on a custom STM32 microcontroller board with only 128KB Flash and 40KB running a HTTP server by becoming a USB Ethernet Adapter.

Link to [Repo](https://github.com/maor1993/stamrust/)

## Length:
30-40 Minutes

**Who are  you?**
Hi, I'm Maor.
Currently a Digital Design Engineer at ARBE robotics
Been doing embedded, board design, FPGA and system design for the past 11 years.
Now starting to add rust to my toolbox 😉

**Comment by szabgab** [comment]
Nice. Do you have a homepage and/or a LinkedIn profile I'll be able to link to?
It would be also nice to get your full name.
Will you bring a few of these board or do you know a vendor of it in Israel who might want to bring a few (and hopefully sell some?)

**Comment by maor1993** [comment]
https://www.linkedin.com/in/maor-malka-a46640134/
Maor Malka.

I will bring a demo and also a bunch of these boards to probably give away :)

**Comment by szabgab** [comment]
Excellent, then I put this as one of the talks.

**Comment by szabgab** [comment]
Do you have a preference of being the first or the second speaker?

**Comment by maor1993** [comment]
Hey! 
no specific preference, what ever works.

**Comment by szabgab** [comment]
Done on 2024.05.09 See https://rust.org.il/code-mavens
Thank you.
