### ISSUE TITLE
Implementing a Neural Network in Rust

### ISSUE THREAD

**Issue by vaktibabat** [szabgab/rust.org.il#9]
Title: Implementing a Neural Network in Rust

## Description:

Neural Networks are one of the most popular models in Machine Learning, and are the basis for a lot of popular AI applications, such as Computer Vision (CV), Natural Language Processing (NLP), and more. In this presentation, I show the math behind Neural Nets, how to train them, and how I implemented one in Rust from scratch to recognize digits in images.
The presentation is based on a post I wrote: https://vaktibabat.github.io/posts/Rust_WASM_Digit_Recognition_1/

## Length:

40 minutes

## On-line or in-person?

In-person

## Date?

23/06/2024

## Who are  you?

I am a third-year CS student at the Open University. Other than that, I am very interested in cybersecurity, reverse engineering, Malware Analysis, AI, and Rust (for about 6 months). I run a blog [here](https://vaktibabat.github.io).
Linkedin Account: [https://www.linkedin.com/in/yoray-herzberg-b8155621b/](https://www.linkedin.com/in/yoray-herzberg-b8155621b/)

Thanks, Yoray Herzberg :)

**Comment by vaktibabat** [comment]
@szabgab Are there any updates?

**Comment by szabgab** [comment]
Sorry for the delay. This sounds good, but can you shorten the presentation to be about 20 minutes? It would be better to give 20 min now and 20 min at another time.

**Comment by vaktibabat** [comment]
Hi, yes, I can shorten it to be 20min.

**Comment by szabgab** [comment]
Excellent, so this will be one of the presentations.

**Comment by szabgab** [comment]
Done on 2024.06.23 Thank you
